context("Multilocus genotype tests")

test_that("multilocus genotype vector is same length as samples", {
  data(Aeut, package = "poppr")
  data(partial_clone, package = "poppr")
  data(nancycats, package = "adegenet")
  amlg <- mlg.vector(Aeut)
  pmlg <- mlg.vector(partial_clone)
  nmlg <- mlg.vector(nancycats)
  expect_that(length(amlg), equals(nInd(Aeut)))
  expect_that(length(pmlg), equals(nInd(partial_clone)))
  expect_that(length(nmlg), equals(nInd(nancycats)))
  expect_that(length(unique(amlg)), equals(mlg(Aeut, quiet = TRUE)))
  expect_that(length(unique(pmlg)), equals(mlg(partial_clone, quiet = TRUE)))
  expect_that(length(unique(nmlg)), equals(mlg(nancycats, quiet = TRUE)))
})

test_that("multilocus genotype matrix matches mlg.vector and data", {
  data(Aeut, package = "poppr")
  data(partial_clone, package = "poppr")
  data(nancycats, package = "adegenet")
  aclone <- as.genclone(Aeut)
  atab   <- mlg.table(Aeut, bar = FALSE)
  ptab   <- mlg.table(partial_clone, bar = FALSE)
  ntab   <- mlg.table(nancycats, bar = FALSE)
  expect_that(nrow(atab), equals(length(Aeut@pop.names)))
  expect_that(nrow(ptab), equals(length(partial_clone@pop.names)))
  expect_that(nrow(ntab), equals(length(nancycats@pop.names)))
  expect_that(ncol(atab), equals(mlg(Aeut, quiet = TRUE)))
  expect_that(ncol(ptab), equals(mlg(partial_clone, quiet = TRUE)))
  expect_that(ncol(ntab), equals(mlg(nancycats, quiet = TRUE)))
  expect_that(sum(atab), equals(nInd(Aeut)))
  expect_that(sum(ptab), equals(nInd(partial_clone)))
  expect_that(sum(ntab), equals(nInd(nancycats)))
})