<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Analysis of Multilocus Genotypes and Lineages in poppr `r packageVersion('poppr')` • poppr</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Analysis of Multilocus Genotypes and Lineages in poppr `r packageVersion('poppr')`">
<meta property="og:description" content="">
<meta property="og:image" content="/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">poppr</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">2.8.3</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/poppr-package.html#functions-in-poppr">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/mlg.html">Analysis of Multilocus Genotypes and Lineages in poppr `r packageVersion('poppr')`</a>
    </li>
    <li>
      <a href="../articles/poppr_manual.html">Data import and manipulation in poppr version `r packageVersion('poppr')`</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/grunwaldlab/poppr">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Analysis of Multilocus Genotypes and Lineages in poppr 2.8.3</h1>
                        <h4 class="author">Zhian N. Kamvar and Niklaus J. Grünwald</h4>
            
            <h4 class="date">2020-02-12</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/grunwaldlab/poppr/blob/master/vignettes/mlg.Rmd"><code>vignettes/mlg.Rmd</code></a></small>
      <div class="hidden name"><code>mlg.Rmd</code></div>

    </div>

    
    
<hr>
<div id="abstract" class="section level1">
<h1 class="hasAnchor">
<a href="#abstract" class="anchor"></a>Abstract</h1>
<p>A multilocus genotype is a unique combination of alleles across two or more loci. For organisms such as plant pathogens that often reproduce clonally, multilocus genotypes are invaluable for identifying the mode and spread of an organism. This document will describe in detail how you can define multilocus genotypes/lineages and how you can use them for your analyses of both genclone and snpclone objects.</p>
<p><br><br></p>
<center>
<img src="jalapeno_logo.png" width="300">
</center>
<hr>
</div>
<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
</div>
<div id="multilocus-genotype-flavors" class="section level1">
<h1 class="hasAnchor">
<a href="#multilocus-genotype-flavors" class="anchor"></a>Multilocus Genotype Flavors</h1>
<p>There are three different ways for constructing multilocus genotypes in <em>poppr</em>.</p>
<table class="table">
<thead><tr class="header">
<th>Method</th>
<th>Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>"original"</code></td>
<td>Default MLG definition; strict matching</td>
</tr>
<tr class="even">
<td><code>"contracted"</code></td>
<td>Collapsing MLGs by genetic distance with <code>mlg.filter</code>
</td>
</tr>
<tr class="odd">
<td><code>"custom"</code></td>
<td>User-defined multilocus genotypes</td>
</tr>
</tbody>
</table>
<p>The first is a simply naïve construction where all alleles must match to make a unique multilocus genotype. New in version 2.0 is the ability to use genetic distance to collapse multilocus genotypes or define custom multilocus lineages based on other information. You can use the function <code><a href="../reference/mll-method.html">mll()</a></code> to display and switch between different multilocus genotypes/lineages.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="st">"poppr"</span>)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="kw"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(monpop)</span>
<span id="cb1-3"><a href="#cb1-3"></a>monpop</span></code></pre></div>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    264 multilocus genotypes 
##    694 haploid individuals
##     13 codominant loci
## 
## Population information:
## 
##      1 stratum - Pop
##     12 populations defined - 
## 7_09_BB, 26_09_BB, 26_09_FR, ..., 45_10_FR, 26_11_BB, 26_11_FR</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="kw"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(<span class="kw"><a href="../reference/mll-method.html">mll</a></span>(monpop, <span class="st">"original"</span>), <span class="dv">20</span>) <span class="co"># Showing the definitions for the first 20 samples</span></span></code></pre></div>
<pre><code>## Warning: 
##  The @mlg slot does not contain an MLG class object.
##  Returning the original mlgs. Please use:
## 
##  mll(monpop) &lt;- "original"
##  
##  to convert your object.</code></pre>
<pre><code>##  [1] 260 179 169 168 167 221 152 133 144  78  78  79  81  44  41  40  40  38 119
## [20] 118</code></pre>
<p>Notice how we got a warning. This is because the <code>monpop</code> data set was created before <code><a href="../reference/mll-method.html">mll()</a></code> was implemented. Luckily, this warning gives us information on how to fix it.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(monpop) &lt;-<span class="st"> "original"</span></span>
<span id="cb6-2"><a href="#cb6-2"></a>monpop</span></code></pre></div>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    264 original multilocus genotypes 
##    694 haploid individuals
##     13 codominant loci
## 
## Population information:
## 
##      1 stratum - Pop
##     12 populations defined - 
## 7_09_BB, 26_09_BB, 26_09_FR, ..., 45_10_FR, 26_11_BB, 26_11_FR</code></pre>
<p>We can see that the description says 264 <strong>original</strong> multilocus genotypes . This is how we know what the current MLG definition is for our object. Let’ see what happens when we change it.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(monpop) &lt;-<span class="st"> "custom"</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>monpop</span></code></pre></div>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    264 custom multilocus genotypes 
##    694 haploid individuals
##     13 codominant loci
## 
## Population information:
## 
##      1 stratum - Pop
##     12 populations defined - 
## 7_09_BB, 26_09_BB, 26_09_FR, ..., 45_10_FR, 26_11_BB, 26_11_FR</code></pre>
<p>Now it says 264 <strong>custom</strong> multilocus genotypes . Of course, if we look at the MLGs, we will see that they appear to be the same as our original definition:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="kw"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(<span class="kw"><a href="../reference/mll-method.html">mll</a></span>(monpop, <span class="st">"custom"</span>), <span class="dv">20</span>) <span class="co"># Showing the definitions for the first 20 samples</span></span></code></pre></div>
<pre><code>##  [1] 260 179 169 168 167 221 152 133 144 78  78  79  81  44  41  40  40  38  119
## [20] 118
## 264 Levels: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 ... 264</code></pre>
<p>All of these functions will work for both <strong>genclone</strong> and <strong>snpclone</strong> objects. In this section, we will demonstrate how to construct each of these three multilocus genotype definitions in different data sets.</p>
<div id="naïve-original" class="section level2">
<h2 class="hasAnchor">
<a href="#na%C3%AFve-original" class="anchor"></a>Naïve (“original”)</h2>
<p>This is the default way <em>poppr</em> calculates multilocus genotypes. You see it immediately when you load a genclone object. Let’s use the example <code>monpop</code> from <span class="citation">(Everhart and Scherm 2015)</span>. First, we need to reset the data to our original MLGs.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(monpop) &lt;-<span class="st"> "original"</span></span>
<span id="cb12-2"><a href="#cb12-2"></a>monpop</span></code></pre></div>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    264 original multilocus genotypes 
##    694 haploid individuals
##     13 codominant loci
## 
## Population information:
## 
##      1 stratum - Pop
##     12 populations defined - 
## 7_09_BB, 26_09_BB, 26_09_FR, ..., 45_10_FR, 26_11_BB, 26_11_FR</code></pre>
<p>You notice that there are 694 samples, yet only 264 multilocus genotypes in the data set over 13 loci. In this sub-section, I will demonstrate how these MLGs are constructed.</p>
<p>The naïve definition simply takes strings of alleles and compares them for equality. This method is quick and easily interpretable, but means that things like genotyping error, hyper-variable loci, and missing data all contribute to a unique genotype that might not be truly unique <span class="citation">(Kamvar, Brooks, and Grünwald 2015)</span>.</p>
<p>To give an example, let’s imagine that we have five samples with alleles typed at two loci.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>grid_example &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1</span>, <span class="dv">4</span>,</span>
<span id="cb14-2"><a href="#cb14-2"></a>                         <span class="dv">1</span>, <span class="dv">1</span>,</span>
<span id="cb14-3"><a href="#cb14-3"></a>                         <span class="dv">5</span>, <span class="dv">1</span>,</span>
<span id="cb14-4"><a href="#cb14-4"></a>                         <span class="dv">9</span>, <span class="dv">1</span>,</span>
<span id="cb14-5"><a href="#cb14-5"></a>                         <span class="dv">9</span>, <span class="dv">4</span>),</span>
<span id="cb14-6"><a href="#cb14-6"></a>                       <span class="dt">ncol =</span> <span class="dv">2</span>,</span>
<span id="cb14-7"><a href="#cb14-7"></a>                       <span class="dt">byrow =</span> <span class="ot">TRUE</span>)</span>
<span id="cb14-8"><a href="#cb14-8"></a><span class="kw"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span>(grid_example) &lt;-<span class="st"> </span>LETTERS[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>]</span>
<span id="cb14-9"><a href="#cb14-9"></a><span class="kw"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span>(grid_example) &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"x"</span>, <span class="st">"y"</span>)</span>
<span id="cb14-10"><a href="#cb14-10"></a>grid_example</span></code></pre></div>
<pre><code>##   x y
## A 1 4
## B 1 1
## C 5 1
## D 9 1
## E 9 4</code></pre>
<p>We notice how they all have different multilocus genotypes. Indeed, if we analyze them, we see that there are five multilocus genotypes.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="st">"poppr"</span>)</span>
<span id="cb16-2"><a href="#cb16-2"></a>x &lt;-<span class="st"> </span><span class="kw"><a href="../reference/coercion-methods.html">as.genclone</a></span>(<span class="kw">df2genind</span>(grid_example, <span class="dt">ploidy =</span> <span class="dv">1</span>))</span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="kw">tab</span>(x)  <span class="co"># Look at the multilocus genotype table</span></span></code></pre></div>
<pre><code>##   x.1 x.5 x.9 y.4 y.1
## A   1   0   0   1   0
## B   1   0   0   0   1
## C   0   1   0   0   1
## D   0   0   1   0   1
## E   0   0   1   1   0</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="kw"><a href="../reference/mll-method.html">nmll</a></span>(x) <span class="co"># count the number of multilocus genotypes</span></span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(x)  <span class="co"># show the multilocus genotype definitions</span></span></code></pre></div>
<pre><code>## [1] 5 4 3 1 2</code></pre>
<p>What we did above was to analyze the <strong>tab</strong> slot of the object showing the counts of alleles per sample across the two loci. We can clearly see by eye that no two samples are alike. The <code><a href="../reference/mll-method.html">nmll()</a></code> function counts the <strong>n</strong>umber of <strong>m</strong>ulti<strong>l</strong>ocus <strong>l</strong>ineages in the sample. the <code><a href="../reference/mll-method.html">mll()</a></code> function displays the assignment of the multilocus lineages in the sample.</p>
<blockquote>
<p>Note: we used <code><a href="../reference/mll-method.html">mll()</a></code> to show us our multilocus lineages. Later on, we will use this same function to switch between different definitions. See ?mll for details.</p>
</blockquote>
<p>Now let’s say we included another sample with partial missing data. Let’s say it was typed as allele “5” at the <strong>x</strong> locus, but missing the allele at the <strong>y</strong> locus.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>x &lt;-<span class="st"> </span><span class="kw"><a href="../reference/coercion-methods.html">as.genclone</a></span>(<span class="kw">df2genind</span>(<span class="kw"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span>(grid_example, <span class="dt">new =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">5</span>, <span class="ot">NA</span>)), <span class="dt">ploidy =</span> <span class="dv">1</span>))</span>
<span id="cb22-2"><a href="#cb22-2"></a><span class="kw">tab</span>(x)  <span class="co"># Note the missing data at locus 2.</span></span></code></pre></div>
<pre><code>##     x.1 x.5 x.9 y.4 y.1
## A     1   0   0   1   0
## B     1   0   0   0   1
## C     0   1   0   0   1
## D     0   0   1   0   1
## E     0   0   1   1   0
## new   0   1   0  NA  NA</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="kw"><a href="../reference/mll-method.html">nmll</a></span>(x)</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(x)</span></code></pre></div>
<pre><code>## [1] 6 5 3 1 2 4</code></pre>
<p>Now we see that we have 6 multilocus genotypes even though one of them contains missing data.</p>
<p>Let’s also imagine that we included yet another sample that had a low-frequency allele at locus <strong>y</strong>, “2”, but had the allele “5” at locus <strong>x</strong>.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a>grid_new &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span>(grid_example,</span>
<span id="cb28-2"><a href="#cb28-2"></a>                  <span class="dt">new =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">5</span>, <span class="ot">NA</span>),</span>
<span id="cb28-3"><a href="#cb28-3"></a>                  <span class="dt">mut =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">5</span>, <span class="dv">2</span>)</span>
<span id="cb28-4"><a href="#cb28-4"></a>                  )</span>
<span id="cb28-5"><a href="#cb28-5"></a>x &lt;-<span class="st"> </span><span class="kw"><a href="../reference/coercion-methods.html">as.genclone</a></span>(<span class="kw">df2genind</span>(grid_new, <span class="dt">ploidy =</span> <span class="dv">1</span>))</span>
<span id="cb28-6"><a href="#cb28-6"></a><span class="kw">tab</span>(x)</span></code></pre></div>
<pre><code>##     x.1 x.5 x.9 y.4 y.1 y.2
## A     1   0   0   1   0   0
## B     1   0   0   0   1   0
## C     0   1   0   0   1   0
## D     0   0   1   0   1   0
## E     0   0   1   1   0   0
## new   0   1   0  NA  NA  NA
## mut   0   1   0   0   0   1</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="kw"><a href="../reference/mll-method.html">nmll</a></span>(x)</span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(x)</span></code></pre></div>
<pre><code>## [1] 7 6 4 1 2 5 3</code></pre>
<p>Again, we get completely different genotypes, but notice how the genotypes we added are closer to the genotype that shares the 5 allele. The reason this happens is because the naïve algorithm reports the rank of the concatenated alleles like so:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a>(xt &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/apply.html">apply</a></span>(<span class="kw">tab</span>(x), <span class="dv">1</span>, paste, <span class="dt">collapse =</span> <span class="st">""</span>))</span></code></pre></div>
<pre><code>##           A           B           C           D           E         new 
##    "100100"    "100010"    "010010"    "001010"    "001100" "010NANANA" 
##         mut 
##    "010001"</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a><span class="kw"><a href="https://rdrr.io/r/base/rank.html">rank</a></span>(xt, <span class="dt">ties.method =</span> <span class="st">"first"</span>)</span></code></pre></div>
<pre><code>##   A   B   C   D   E new mut 
##   7   6   4   1   2   5   3</code></pre>
<p>Even though we have reason to believe that the samples “new” and “mut” might actually have the genotype x.5 and y.1 (the MLG of sample C), the algorithm sees them as different. If we calculate the pairwise euclidean distances between samples, we see that “new”, “mut” and, “C” are very similar to each other:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="st">"phangorn"</span>)</span>
<span id="cb38-2"><a href="#cb38-2"></a><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="st">"ape"</span>)</span>
<span id="cb38-3"><a href="#cb38-3"></a>raw_dist &lt;-<span class="st"> </span><span class="cf">function</span>(x){</span>
<span id="cb38-4"><a href="#cb38-4"></a>  <span class="kw"><a href="https://rdrr.io/r/stats/dist.html">dist</a></span>(<span class="kw">genind2df</span>(x, <span class="dt">usepop =</span> <span class="ot">FALSE</span>))</span>
<span id="cb38-5"><a href="#cb38-5"></a>}</span>
<span id="cb38-6"><a href="#cb38-6"></a>(xdis &lt;-<span class="st"> </span><span class="kw">raw_dist</span>(x))</span></code></pre></div>
<pre><code>##            A        B        C        D        E      new
## B   3.000000                                             
## C   5.000000 4.000000                                    
## D   8.544004 8.000000 4.000000                           
## E   8.000000 8.544004 5.000000 3.000000                  
## new 5.656854 5.656854 0.000000 5.656854 5.656854         
## mut 4.472136 4.123106 1.000000 4.123106 4.472136 0.000000</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="kw"><a href="https://rdrr.io/pkg/ape/man/plot.phylo.html">plot.phylo</a></span>(<span class="kw"><a href="https://rdrr.io/pkg/phangorn/man/upgma.html">upgma</a></span>(xdis))</span></code></pre></div>
<p><img src="mlg_files/figure-html/unnamed-chunk-12-1.png" width="480" style="display: block; margin: auto;"></p>
<p>Therefore, we might want to consider “new”, “mut” and, “C” to be the same Multilocus Lineage (MLL). In the next section, you will see how to collapse multilocus genotypes by genetic distance.</p>
</div>
<div id="filtered-contracted" class="section level2">
<h2 class="hasAnchor">
<a href="#filtered-contracted" class="anchor"></a>Filtered (“contracted”)</h2>
<p>To remedy the issues with a naïve definition of multilocus genotypes, we can utilize genetic distance, which will allow us to collapse multilocus genotypes that are under a specific distance threshold. The main function we will use in this section is <code><a href="../reference/mlg.filter.html">mlg.filter()</a></code>. It will create a dissimiliarity distance matrix from the data and then filter based off of that matrix. You can also utilize your own supplied distance matrix or distance function.</p>
<div id="main-usage" class="section level3">
<h3 class="hasAnchor">
<a href="#main-usage" class="anchor"></a>Main usage</h3>
<p>To use <code><a href="../reference/mlg.filter.html">mlg.filter()</a></code>, you need to define a thresold. This threshold defines the minimum distance to consider two genotypes unique, so anything below that will be clustered into the same MLG. In practice, it’s used like this (using the data and the euclidean distance described above):</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>x <span class="co"># We have 7 MLGs before filtering</span></span></code></pre></div>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    7 original multilocus genotypes 
##    7 haploid individuals
##    2 codominant loci
## 
## Population information:
## 
##    0 strata. 
##    0 populations defined.</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a><span class="kw"><a href="../reference/mlg.filter.html">mlg.filter</a></span>(x, <span class="dt">distance =</span> xdis) &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>.Machine<span class="op">$</span>double.eps<span class="op">^</span><span class="fl">0.5</span></span>
<span id="cb43-2"><a href="#cb43-2"></a>x <span class="co"># Now we have 5 MLGs</span></span></code></pre></div>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    5 contracted multilocus genotypes
##      (1) [t], (xdis) [d], (farthest) [a] 
##    7 haploid individuals
##    2 codominant loci
## 
## Population information:
## 
##    0 strata. 
##    0 populations defined.</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(x) &lt;-<span class="st"> "original"</span> <span class="co"># We'll reset to the naive definition</span></span></code></pre></div>
<p>Here, we told <code><a href="../reference/mlg.filter.html">mlg.filter()</a></code> to set the threshold to 1 plus a very tiny number (this will be explained in the next section) based off of the distance matrix <strong>xdis</strong>. This is a way to manipulate the object in place. In this section, there will be examples of retrieving the MLGs and other statistics from the function as well as how to use different distance functions and reset the MLGs.</p>
</div>
<div id="thresholds" class="section level3">
<h3 class="hasAnchor">
<a href="#thresholds" class="anchor"></a>Thresholds</h3>
<p>As we saw above, in order to collapse all three new samples into the original 5 MLGs, we had to set a threshold of <em>just above</em> 1. To show you why, we will use the function to return to us the MLGs it created and the thresholds that were passed to cluster MLLs (by using the <code>stats</code> argument).</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(x, <span class="st">"original"</span>)</span></code></pre></div>
<pre><code>## [1] 7 6 4 1 2 5 3</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="kw"><a href="../reference/mlg.filter.html">mlg.filter</a></span>(x, <span class="dt">distance =</span> xdis, <span class="dt">threshold =</span> <span class="dv">1</span>, <span class="dt">stats =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"mlg"</span>, <span class="st">"thresholds"</span>))</span></code></pre></div>
<pre><code>## $MLGS
## [1] 7 6 4 1 2 3 3
## 
## $THRESHOLDS
## [1] 0</code></pre>
<p>In our output, we can see that MLG 5 has collapsed into MLG 3. This occured as soon as our threshold passed 0. Take a look at what happens when we add a very small number to 1.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a>(e &lt;-<span class="st"> </span>.Machine<span class="op">$</span>double.eps<span class="op">^</span><span class="fl">0.5</span>) <span class="co"># A very tiny number</span></span></code></pre></div>
<pre><code>## [1] 1.490116e-08</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a><span class="kw"><a href="../reference/mlg.filter.html">mlg.filter</a></span>(x, <span class="dt">distance =</span> xdis, <span class="dt">threshold =</span> <span class="dv">1</span> <span class="op">+</span><span class="st"> </span>e, <span class="dt">stats =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"mlg"</span>, <span class="st">"thresholds"</span>))</span></code></pre></div>
<pre><code>## $MLGS
## [1] 7 6 4 1 2 4 4
## 
## $THRESHOLDS
## [1] 0 1</code></pre>
<p>Now that we have set the threshold to <em>just above</em> 1, we have 5 unique MLLs since MLG 3 collapsed into MLG 4. Because of the way clustering happens, it’s important to point out what happens when you attempt to use a threshold of 0.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a><span class="kw"><a href="../reference/mlg.filter.html">mlg.filter</a></span>(x, <span class="dt">distance =</span> xdis, <span class="dt">threshold =</span> <span class="dv">0</span>, <span class="dt">stats =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"mlg"</span>, <span class="st">"thresholds"</span>))</span></code></pre></div>
<pre><code>## $MLGS
## [1] 7 6 4 1 2 5 3
## 
## $THRESHOLDS
## numeric(0)</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(x, <span class="st">"original"</span>)</span></code></pre></div>
<pre><code>## [1] 7 6 4 1 2 5 3</code></pre>
<p>Notice that all the MLGs are the same as the originally defined MLGs. Using a threshold of zero allows two MLGs separated by zero genetic distance to remain mutually unique.</p>
</div>
<div id="setting-the-genotypes" class="section level3">
<h3 class="hasAnchor">
<a href="#setting-the-genotypes" class="anchor"></a>Setting the genotypes</h3>
<p>As demonstrated at the beginning of this section, if we wanted to reassign our sample genotypes to the collapsed version, all we would have to do is use the <code><a href="../reference/mlg.filter.html">mlg.filter()</a></code> commands above, but use the <code>&lt;-</code> operator to specify the threshold. Note that I will be using <code><a href="../reference/mlg.html">mlg.table()</a></code> to show the distribution of the multilocus genotypes before and after filtering.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1"></a>x</span></code></pre></div>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    7 original multilocus genotypes 
##    7 haploid individuals
##    2 codominant loci
## 
## Population information:
## 
##    0 strata. 
##    0 populations defined.</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1"></a><span class="kw"><a href="../reference/mlg.html">mlg.table</a></span>(x) <span class="co"># Before: 7 MLGs</span></span></code></pre></div>
<p><img src="mlg_files/figure-html/unnamed-chunk-17-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>##       MLG.1 MLG.2 MLG.3 MLG.4 MLG.5 MLG.6 MLG.7
## Total     1     1     1     1     1     1     1</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a><span class="kw"><a href="../reference/mlg.filter.html">mlg.filter</a></span>(x, <span class="dt">distance =</span> xdis) &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>e</span>
<span id="cb62-2"><a href="#cb62-2"></a>x</span></code></pre></div>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    5 contracted multilocus genotypes
##      (1) [t], (xdis) [d], (farthest) [a] 
##    7 haploid individuals
##    2 codominant loci
## 
## Population information:
## 
##    0 strata. 
##    0 populations defined.</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1"></a><span class="kw"><a href="../reference/mlg.html">mlg.table</a></span>(x) <span class="co"># After: 5 MLGs</span></span></code></pre></div>
<p><img src="mlg_files/figure-html/unnamed-chunk-17-2.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>##       MLG.1 MLG.2 MLG.4 MLG.6 MLG.7
## Total     1     1     3     1     1</code></pre>
<p>Notice how the information you see has changed. You can see that it’s printed out that you have 5 <strong>contracted</strong> multilocus genotypes, but you have some cryptic code underneath:</p>
<table class="table">
<thead><tr class="header">
<th align="center">symbol</th>
<th align="left">meaning</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center"><strong>[t]</strong></td>
<td align="left">threshold</td>
</tr>
<tr class="even">
<td align="center"><strong>[d]</strong></td>
<td align="left">distance (can be matrix or function)</td>
</tr>
<tr class="odd">
<td align="center"><strong>[a]</strong></td>
<td align="left">algorithm (see the next section)</td>
</tr>
</tbody>
</table>
<p>Genclone and snpclone objects will always remember what parameters were used for filtering multilocus genotypes, but the only catch is that, if you use your own supplied distance (matrix or function), you must be very careful not to delete it or change the object name.</p>
<p>This means that you don’t always have to specify the distance when assigning a threshold:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1"></a><span class="kw"><a href="../reference/mlg.filter.html">mlg.filter</a></span>(x) &lt;-<span class="st"> </span><span class="fl">4.51</span></span>
<span id="cb66-2"><a href="#cb66-2"></a>x</span></code></pre></div>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    3 contracted multilocus genotypes
##      (4.51) [t], (xdis) [d], (farthest) [a] 
##    7 haploid individuals
##    2 codominant loci
## 
## Population information:
## 
##    0 strata. 
##    0 populations defined.</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1"></a><span class="kw"><a href="../reference/mlg.html">mlg.table</a></span>(x)</span></code></pre></div>
<p><img src="mlg_files/figure-html/unnamed-chunk-18-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>##       MLG.1 MLG.4 MLG.6
## Total     2     3     2</code></pre>
<blockquote>
<p>DANGER! DANGER! While this is a convenient function, if you use a matrix or function that was created by you, you <strong>must not delete it or change its name</strong>. Only the name of the matrix/function is stored, so if you delete the matrix/function used to inform your filtering, you will get an error:</p>
</blockquote>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1"></a><span class="kw"><a href="https://rdrr.io/r/base/rm.html">rm</a></span>(xdis) <span class="co"># NOOOOOO!</span></span>
<span id="cb70-2"><a href="#cb70-2"></a><span class="kw"><a href="https://rdrr.io/r/base/try.html">try</a></span>(<span class="kw"><a href="../reference/mlg.filter.html">mlg.filter</a></span>(x) &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>e)</span></code></pre></div>
<pre><code>## Error : cannot evaluate distance function, it might be missing.</code></pre>
<pre><code>##  Error: cannot evaluate distance function, it might be missing.</code></pre>
<p>Basically, your object thinks that there should be a matrix called <strong>xdis</strong>, but it can’t find it anywhere. But don’t worry, we can restore it if we have the function available. We will use the <code>raw_dist()</code> function that we defined earlier.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1"></a><span class="kw"><a href="../reference/mlg.filter.html">mlg.filter</a></span>(x, <span class="dt">distance =</span> raw_dist) &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>e</span>
<span id="cb73-2"><a href="#cb73-2"></a>x</span></code></pre></div>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    5 contracted multilocus genotypes
##      (1) [t], (raw_dist) [d], (farthest) [a] 
##    7 haploid individuals
##    2 codominant loci
## 
## Population information:
## 
##    0 strata. 
##    0 populations defined.</code></pre>
<p>The safest way, perhaps, is to use a function defined in <em>poppr</em>. For example, we’ll use Bruvo’s distance since it takes into account the real value of the alleles <span class="citation">(Bruvo et al. 2004)</span>.</p>
<blockquote>
<p>The arguments to your distance function will be stored in the object as well!</p>
</blockquote>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1"></a><span class="kw"><a href="../reference/bruvo.dist.html">bruvo.dist</a></span>(x, <span class="dt">replen =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<pre><code>##             A         B         C         D         E       new
## B   0.4375000                                                  
## C   0.9062500 0.4687500                                        
## D   0.9355469 0.4980469 0.4687500                              
## E   0.4980469 0.9355469 0.9062500 0.4375000                    
## new 0.9375000 0.9375000 0.0000000 0.9375000 0.9375000          
## mut 0.8437500 0.7187500 0.2500000 0.7187500 0.8437500 0.0000000</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1"></a><span class="kw"><a href="../reference/mlg.filter.html">mlg.filter</a></span>(x, <span class="dt">distance =</span> bruvo.dist, <span class="dt">replen =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1</span>, <span class="dv">1</span>)) &lt;-<span class="st"> </span><span class="fl">0.44</span></span>
<span id="cb77-2"><a href="#cb77-2"></a>x</span></code></pre></div>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    3 contracted multilocus genotypes
##      (0.44) [t], (bruvo.dist) [d], (farthest) [a] 
##    7 haploid individuals
##    2 codominant loci
## 
## Population information:
## 
##    0 strata. 
##    0 populations defined.</code></pre>
<p>Of course, our multilocus genotypes are not changed forever, they are just stored in a different place. We can access the original, naïve multilocus genotypes by using the <code><a href="../reference/mll-method.html">mll()</a></code> function:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(x, <span class="st">"original"</span>)</span></code></pre></div>
<pre><code>## [1] 7 6 4 1 2 5 3</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(x) <span class="co"># contracted</span></span></code></pre></div>
<pre><code>## [1] 6 6 4 1 1 4 4</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(x) &lt;-<span class="st"> "original"</span></span>
<span id="cb83-2"><a href="#cb83-2"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(x) <span class="co"># original</span></span></code></pre></div>
<pre><code>## [1] 7 6 4 1 2 5 3</code></pre>
</div>
<div id="tie-breakers-algorithms" class="section level3">
<h3 class="hasAnchor">
<a href="#tie-breakers-algorithms" class="anchor"></a>Tie breakers (algorithms)</h3>
<p>Underlying <code>mlg.filter</code> are three algorithms that decide what genotypes go together <span class="citation">(Kamvar, Brooks, and Grünwald 2015)</span>:</p>
<ul>
<li>nearest neighbor</li>
<li>farthest neighbor (default)</li>
<li>average neighbor (UPGMA)</li>
</ul>
<p>You can specify which algorithm you want to use in clustering with the <code>algorithm</code> argument. Each of these algorithms have different behaviors when it comes to collapsing multilocus genotypes. In short, farthest neighbor is the most conservative, nearest neighbor can have a chaining effect, and average neighbor is somewhere in between. Your choice of algorithm really depends on the biology of your organism.</p>
<p>To help visualize this, there is the function <code><a href="../reference/filter_stats.html">filter_stats()</a></code>, which will plot the output of the filtering algorithm. For simplicity, we will use the <code>Pinf</code> data set representing <em>Phytophthora infestans</em> samples from Mexico and South America <span class="citation">(Goss et al. 2009)</span>.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1"></a><span class="kw"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(Pinf)</span>
<span id="cb85-2"><a href="#cb85-2"></a>Pinf</span></code></pre></div>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    72 multilocus genotypes 
##    86 tetraploid individuals
##    11 codominant loci
## 
## Population information:
## 
##     2 strata - Continent, Country
##     2 populations defined - South America, North America</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1"></a>pinfreps &lt;-<span class="st"> </span><span class="kw"><a href="../reference/fix_replen.html">fix_replen</a></span>(Pinf, <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">6</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">2</span>))</span>
<span id="cb87-2"><a href="#cb87-2"></a>pinf_filtered &lt;-<span class="st"> </span><span class="kw"><a href="../reference/filter_stats.html">filter_stats</a></span>(Pinf, <span class="dt">distance =</span> bruvo.dist, <span class="dt">replen =</span> pinfreps, <span class="dt">plot =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="mlg_files/figure-html/plot_replen-1.png" width="700" style="display: block; margin: auto;"></p>
<p>We can see that the different algorithms behave similarly for small thresholds, but begin to differ over larger thresholds.</p>
<p>This function is useful for finding all thresholds at which MLLs are collapsed, which can help with choosing a threshold that collapses putative clones in our sample into lineages.</p>
</div>
<div id="choosing-a-threshold" class="section level3">
<h3 class="hasAnchor">
<a href="#choosing-a-threshold" class="anchor"></a>Choosing a threshold</h3>
<p>After you have chosen a genetic distance and a filtering algorithm, you must then decide on the threshold to represent the <strong>minimum genetic distance at which two individuals would be considered from different clonal lineages</strong>.</p>
<p>One method described in the literature of choosing a threshold is to look for an initial, small peak in the histogram of pairwise genetic distances and set the threshold to be between that peak and the larger peak `<span class="citation">(Arnaud-Haond et al. 2007, @bailleul2016rclone)</span>. This initial peak likely represents clones differentiated by a small set of random mutations. You can see this in the figure above at a threshold of ~0.11 for the “farthest neighbor” algorithm.</p>
<p>However, if this peak is not obvious, then another method is to look for the largest gap between all putative thresholds. For this, you can use the <code><a href="../reference/cutoff_predictor.html">cutoff_predictor()</a></code> function with the output of <code><a href="../reference/filter_stats.html">filter_stats()</a></code>. It should be noted that this method is not a perfect solution. If we take the results from above, we can find the threshold for each algorithm:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1"></a><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(farthest_thresh &lt;-<span class="st"> </span><span class="kw"><a href="../reference/cutoff_predictor.html">cutoff_predictor</a></span>(pinf_filtered<span class="op">$</span>farthest<span class="op">$</span>THRESHOLDS))</span></code></pre></div>
<pre><code>## [1] 0.1132221</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1"></a><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(average_thresh  &lt;-<span class="st"> </span><span class="kw"><a href="../reference/cutoff_predictor.html">cutoff_predictor</a></span>(pinf_filtered<span class="op">$</span>average<span class="op">$</span>THRESHOLDS))</span></code></pre></div>
<pre><code>## [1] 0.1084407</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1"></a><span class="kw"><a href="https://rdrr.io/r/base/print.html">print</a></span>(nearest_thresh  &lt;-<span class="st"> </span><span class="kw"><a href="../reference/cutoff_predictor.html">cutoff_predictor</a></span>(pinf_filtered<span class="op">$</span>nearest<span class="op">$</span>THRESHOLDS))</span></code></pre></div>
<pre><code>## [1] 0.1092773</code></pre>
<p>Now we can define multilocus lineages for <em>P. infestans</em> with the following criteria:</p>
<table class="table"><tbody>
<tr class="odd">
<td align="center"><strong>[t]</strong></td>
<td align="left">threshold</td>
<td align="left">0.113</td>
</tr>
<tr class="even">
<td align="center"><strong>[d]</strong></td>
<td align="left">distance</td>
<td align="left">Bruvo’s Distance</td>
</tr>
<tr class="odd">
<td align="center"><strong>[a]</strong></td>
<td align="left">algorithm</td>
<td align="left">Farthest neighbor</td>
</tr>
</tbody></table>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1"></a><span class="kw"><a href="../reference/mlg.filter.html">mlg.filter</a></span>(Pinf, <span class="dt">distance =</span> bruvo.dist, <span class="dt">replen =</span> pinfreps, <span class="dt">algorithm =</span> <span class="st">"f"</span>) &lt;-<span class="st"> </span>farthest_thresh</span>
<span id="cb94-2"><a href="#cb94-2"></a>Pinf</span></code></pre></div>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    48 contracted multilocus genotypes
##       (0.113) [t], (bruvo.dist) [d], (farthest) [a] 
##    86 tetraploid individuals
##    11 codominant loci
## 
## Population information:
## 
##     2 strata - Continent, Country
##     2 populations defined - South America, North America</code></pre>
<blockquote>
<p>Note: Please take care to critically evaluate the results and make sure it applies to your data. This function WILL give you an answer whether or not one truely exists. Additionally, For diploid organisms, another method of choosing a threshold is available in the <strong>RClone</strong> package that involves simulating outcrossing and inbreeding events <span class="citation">(Bailleul, Stoeckel, and Arnaud-Haond 2016)</span>.</p>
</blockquote>
</div>
</div>
<div id="custom-custom" class="section level2">
<h2 class="hasAnchor">
<a href="#custom-custom" class="anchor"></a>Custom (“custom”)</h2>
<p>Sometimes multilocus genotypes are defined by more than just genetic data and it would be useful to be able to analyze these genotype definitions. Luckily, there is a way to do this. <em>Poppr</em> has support for custom multilocus genotypes. For example, we have a simulated data set that has 50 samples with 26 multilocus genotypes.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1"></a><span class="kw"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(partial_clone)</span>
<span id="cb96-2"><a href="#cb96-2"></a>pc &lt;-<span class="st"> </span><span class="kw"><a href="../reference/coercion-methods.html">as.genclone</a></span>(partial_clone)</span>
<span id="cb96-3"><a href="#cb96-3"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(pc)</span></code></pre></div>
<pre><code>##  [1]  8  9 23 24 22 21 10  3 22 11 24  9 25  4 12  2 14  1  9  9  9 26  7 13 23
## [26]  3 17 22  6 20 22 12  5 25 13 21 15 13 13 13  2 19 18 13 23 16  1 11 25  4</code></pre>
<p>Let’s change the MLGs to letters instead of numbers. We will use <code><a href="../reference/mll.custom.html">mll.custom()</a></code> to do this.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1"></a>LETTERS[<span class="kw"><a href="../reference/mll-method.html">mll</a></span>(pc)]  <span class="co"># The new MLGs</span></span></code></pre></div>
<pre><code>##  [1] "H" "I" "W" "X" "V" "U" "J" "C" "V" "K" "X" "I" "Y" "D" "L" "B" "N" "A" "I"
## [20] "I" "I" "Z" "G" "M" "W" "C" "Q" "V" "F" "T" "V" "L" "E" "Y" "M" "U" "O" "M"
## [39] "M" "M" "B" "S" "R" "M" "W" "P" "A" "K" "Y" "D"</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1"></a><span class="kw"><a href="../reference/mll.custom.html">mll.custom</a></span>(pc) &lt;-<span class="st"> </span>LETTERS[<span class="kw"><a href="../reference/mll-method.html">mll</a></span>(pc)]</span>
<span id="cb100-2"><a href="#cb100-2"></a><span class="kw"><a href="../reference/mlg.html">mlg.table</a></span>(pc)</span></code></pre></div>
<p><img src="mlg_files/figure-html/unnamed-chunk-25-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>##   A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
## 1 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 2 2 0 2 0
## 2 1 0 1 2 0 0 0 0 1 0 1 0 1 0 0 1 0 0 1 1 1 0 0 0 1 1
## 3 1 0 0 0 0 0 1 0 1 1 0 1 2 0 0 0 1 1 0 0 0 1 1 1 0 0
## 4 0 1 1 0 0 0 0 0 2 0 1 1 3 0 0 0 0 0 0 0 1 1 0 1 0 0</code></pre>
<p>This even works with minimum spanning networks:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1"></a>pcpal &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/grDevices/colorRamp.html">colorRampPalette</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"blue"</span>, <span class="st">"gold"</span>))</span>
<span id="cb102-2"><a href="#cb102-2"></a><span class="kw"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span>(<span class="dv">9001</span>)</span>
<span id="cb102-3"><a href="#cb102-3"></a>pcmsn &lt;-<span class="st"> </span><span class="kw"><a href="../reference/bruvo.msn.html">bruvo.msn</a></span>(pc, <span class="dt">replen =</span> <span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="dv">1</span>, <span class="kw">nLoc</span>(pc)), <span class="dt">palette =</span> pcpal,</span>
<span id="cb102-4"><a href="#cb102-4"></a>                   <span class="dt">vertex.label.color =</span> <span class="st">"firebrick"</span>, <span class="dt">vertex.label.font =</span> <span class="dv">2</span>,</span>
<span id="cb102-5"><a href="#cb102-5"></a>                   <span class="dt">vertex.label.cex =</span> <span class="fl">1.5</span>)</span></code></pre></div>
<p><img src="mlg_files/figure-html/unnamed-chunk-26-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Let’s say that we realized that we have strong evidence for MLG “Q” being the same as MLG “M”. If we wanted to change those, we could simply change the factor levels:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1"></a><span class="kw"><a href="../reference/mll.custom.html">mll.levels</a></span>(pc)[<span class="kw"><a href="../reference/mll.custom.html">mll.levels</a></span>(pc) <span class="op">==</span><span class="st"> "Q"</span>] &lt;-<span class="st"> "M"</span></span></code></pre></div>
<p>And we can plot again</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1"></a><span class="kw"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span>(<span class="dv">9001</span>)</span>
<span id="cb104-2"><a href="#cb104-2"></a>pcmsn &lt;-<span class="st"> </span><span class="kw"><a href="../reference/bruvo.msn.html">bruvo.msn</a></span>(pc, <span class="dt">replen =</span> <span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="dv">1</span>, <span class="kw">nLoc</span>(pc)), <span class="dt">palette =</span> pcpal,</span>
<span id="cb104-3"><a href="#cb104-3"></a>                   <span class="dt">vertex.label.color =</span> <span class="st">"firebrick"</span>, <span class="dt">vertex.label.font =</span> <span class="dv">2</span>,</span>
<span id="cb104-4"><a href="#cb104-4"></a>                   <span class="dt">vertex.label.cex =</span> <span class="fl">1.5</span>)</span></code></pre></div>
<p><img src="mlg_files/figure-html/unnamed-chunk-28-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Notice how the minimum spanning network architecture stayed the same, but the labels had changed.</p>
</div>
</div>
<div id="diversity-analysis" class="section level1">
<h1 class="hasAnchor">
<a href="#diversity-analysis" class="anchor"></a>Diversity Analysis</h1>
<p>In the <strong>Data Import and Manipulation</strong> vignette, the first command demonstrated was the <code><a href="../reference/poppr.html">poppr()</a></code>, command, which produced a table of diversity statistics, most of which were calculated on counts of multilocus genotypes. These statistics can be replicated by using the function <code><a href="../reference/diversity_stats.html">diversity_stats()</a></code>. This function calculates diversity statistics based off of a table of multilocus genotypes. Let’s analyze the diversity of the peach brown rot pathogen, <em>Monilinia fructicola</em>, structured by Symptom (Fruit Rot:FR and Blossom Blight:BB) and Year <span class="citation">(Everhart and Scherm 2015)</span>. Let’s first look at the distribution of multilocus genotypes:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1"></a><span class="kw"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(monpop)</span>
<span id="cb105-2"><a href="#cb105-2"></a><span class="kw">splitStrata</span>(monpop) &lt;-<span class="st"> </span><span class="er">~</span>Tree<span class="op">/</span>Year<span class="op">/</span>Symptom</span>
<span id="cb105-3"><a href="#cb105-3"></a>montab &lt;-<span class="st"> </span><span class="kw"><a href="../reference/mlg.html">mlg.table</a></span>(monpop, <span class="dt">strata =</span> <span class="op">~</span>Symptom<span class="op">/</span>Year)</span></code></pre></div>
<p><img src="mlg_files/figure-html/unnamed-chunk-29-1.png" width="700" style="display: block; margin: auto;"></p>
<p>We can see from these plots that the Fruit Rot (FR) have a lot more clones in the canopies than Blossom Blight (BB). This makes biological sense since Fruit Rot infections are clonally propagated, whereas Blossom Blight infections are from sexual propagules <span class="citation">(Everhart and Scherm 2015)</span>. Let’s look at the diversity metrics.</p>
<div id="basic-statistics" class="section level2">
<h2 class="hasAnchor">
<a href="#basic-statistics" class="anchor"></a>Basic Statistics</h2>
<p>The function <code><a href="../reference/diversity_stats.html">diversity_stats()</a></code> is used to get basic diversity statistics:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1"></a>(monstat &lt;-<span class="st"> </span><span class="kw"><a href="../reference/diversity_stats.html">diversity_stats</a></span>(montab))</span></code></pre></div>
<pre><code>##        Index
## Pop            H        G    lambda       E.5
##   BB_9  3.580258 25.92405 0.9614258 0.7145086
##   FR_9  3.103899 12.43711 0.9195955 0.5373402
##   BB_10 2.944439 19.00000 0.9473684 1.0000000
##   FR_10 4.066838 38.10132 0.9737542 0.6466786
##   BB_11 3.401197 30.00000 0.9666667 1.0000000
##   FR_11 3.094688 10.48941 0.9046657 0.4501543</code></pre>
</div>
<div id="confidence-intervals" class="section level2">
<h2 class="hasAnchor">
<a href="#confidence-intervals" class="anchor"></a>Confidence Intervals</h2>
<p>We can get confidence intervals for these statistics using <code><a href="../reference/diversity_ci.html">diversity_ci()</a></code>:</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1"></a><span class="kw"><a href="../reference/diversity_ci.html">diversity_ci</a></span>(montab, <span class="dt">n =</span> 100L, <span class="dt">raw =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## 
## Confidence Intervals have been centered around observed statistic.
## Please see ?diversity_ci for details.</code></pre>
<p><img src="mlg_files/figure-html/unnamed-chunk-31-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>##          H H.est           H.ci    G G.est             G.ci lambda lambda.est
## BB_9  3.58  3.19 (3.341, 3.819) 25.9 19.26  (19.298, 32.55)  0.961      0.946
## FR_9  3.10  2.97 (2.912, 3.296) 12.4 11.98  (9.918, 14.956)  0.920      0.916
## BB_10 2.94  2.37 (2.664, 3.225) 19.0  9.81 (15.986, 22.014)  0.947      0.895
## FR_10 4.07  3.87 (3.926, 4.207) 38.1 33.63 (31.199, 45.004)  0.974      0.970
## BB_11 3.40  2.83 (3.173, 3.629) 30.0 15.28 (26.066, 33.934)  0.967      0.933
## FR_11 3.09  2.85 (2.802, 3.387) 10.5  9.81   (6.73, 14.249)  0.905      0.894
##            lambda.ci   E.5 E.5.est         E.5.ci
## BB_9  (0.942, 0.981) 0.715   0.776  (0.599, 0.83)
## FR_9  (0.902, 0.937) 0.537   0.593 (0.488, 0.587)
## BB_10 (0.913, 0.981) 1.000   0.894 (0.921, 1.079)
## FR_10  (0.968, 0.98) 0.647   0.691 (0.579, 0.714)
## BB_11 (0.948, 0.986) 1.000   0.889 (0.936, 1.064)
## FR_11 (0.861, 0.949) 0.450   0.533   (0.35, 0.55)</code></pre>
<p>You can see that there was a warning about centering the confidence interval. The boxplots you see are the distribution of the bootstrapped replicates, but they are known to be biased. We invite users to please read the documentation for <code><a href="../reference/diversity_ci.html">diversity_ci()</a></code> by typing <code><a href="../reference/diversity_ci.html">?diversity_ci</a></code>. It is very important to be careful when interpreting these results because sometimes confidence the confidence intervals exist outside of the possible range, as exemplified by BB_10 and BB_11.</p>
</div>
<div id="custom-statistics" class="section level2">
<h2 class="hasAnchor">
<a href="#custom-statistics" class="anchor"></a>Custom Statistics</h2>
<p>In all of the <code>diversity_*</code> functions, you can use your own custom diversity statistics. A common one we get requests for is the clonal fraction, <span class="math inline">\(\frac{MLG}{N}\)</span> or the number of multilocus genotypes over the number of samples. You can add it in by writing your own function. Keep in mind, that you should write it for both a matrix and a vector of counts if you want to be able to bootstrap it.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1"></a>myCF &lt;-<span class="st"> </span><span class="cf">function</span>(x){</span>
<span id="cb111-2"><a href="#cb111-2"></a> x &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/drop.html">drop</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span>(x))</span>
<span id="cb111-3"><a href="#cb111-3"></a> <span class="cf">if</span> (<span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/dim.html">dim</a></span>(x)) <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span>){ <span class="co"># if it's a matrix</span></span>
<span id="cb111-4"><a href="#cb111-4"></a>   res &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span>(x <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>)<span class="op">/</span><span class="kw"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span>(x)</span>
<span id="cb111-5"><a href="#cb111-5"></a> } <span class="cf">else</span> {                 <span class="co"># if it's a vector</span></span>
<span id="cb111-6"><a href="#cb111-6"></a>   res &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(x <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>)<span class="op">/</span><span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(x)</span>
<span id="cb111-7"><a href="#cb111-7"></a> }</span>
<span id="cb111-8"><a href="#cb111-8"></a> <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(res)</span>
<span id="cb111-9"><a href="#cb111-9"></a>}</span>
<span id="cb111-10"><a href="#cb111-10"></a>(monstat2 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/diversity_stats.html">diversity_stats</a></span>(montab, <span class="dt">CF =</span> myCF))</span></code></pre></div>
<pre><code>##        Index
## Pop            H        G    lambda       E.5        CF
##   BB_9  3.580258 25.92405 0.9614258 0.7145086 0.7031250
##   FR_9  3.103899 12.43711 0.9195955 0.5373402 0.2585366
##   BB_10 2.944439 19.00000 0.9473684 1.0000000 1.0000000
##   FR_10 4.066838 38.10132 0.9737542 0.6466786 0.3405018
##   BB_11 3.401197 30.00000 0.9666667 1.0000000 1.0000000
##   FR_11 3.094688 10.48941 0.9046657 0.4501543 0.4536082</code></pre>
<p>You can use filtered or custom MLGs to compare diversity. Here, I’m filtering genotypes in <code>monpop</code> that are different by only a single mutational step <span class="citation">(Bruvo et al. 2004)</span>.</p>
<blockquote>
<p>One mutational step for a single allele in Bruvo’s distance is equivalent to 0.5, so a single mutational step for a haploid organism with 13 loci is 0.5/13.</p>
</blockquote>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1"></a><span class="co"># Repeat lengths are necessary</span></span>
<span id="cb113-2"><a href="#cb113-2"></a>reps &lt;-<span class="st"> </span><span class="kw"><a href="../reference/fix_replen.html">fix_replen</a></span>(monpop,</span>
<span id="cb113-3"><a href="#cb113-3"></a>                   <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dt">CHMFc4 =</span> <span class="dv">7</span>, <span class="dt">CHMFc5 =</span> <span class="dv">2</span>, <span class="dt">CHMFc12 =</span> <span class="dv">4</span>,</span>
<span id="cb113-4"><a href="#cb113-4"></a>                     <span class="dt">SEA =</span> <span class="dv">4</span>, <span class="dt">SED =</span> <span class="dv">4</span>, <span class="dt">SEE =</span> <span class="dv">2</span>, <span class="dt">SEG =</span> <span class="dv">6</span>,</span>
<span id="cb113-5"><a href="#cb113-5"></a>                     <span class="dt">SEI =</span> <span class="dv">3</span>, <span class="dt">SEL =</span> <span class="dv">4</span>, <span class="dt">SEN =</span> <span class="dv">2</span>,</span>
<span id="cb113-6"><a href="#cb113-6"></a>                     <span class="dt">SEP =</span> <span class="dv">4</span>, <span class="dt">SEQ =</span> <span class="dv">2</span>, <span class="dt">SER =</span> <span class="dv">4</span>))</span>
<span id="cb113-7"><a href="#cb113-7"></a></span>
<span id="cb113-8"><a href="#cb113-8"></a><span class="co"># Adding a little bit, so the threshold is included.</span></span>
<span id="cb113-9"><a href="#cb113-9"></a>e &lt;-<span class="st"> </span>.Machine<span class="op">$</span>double.eps<span class="op">^</span><span class="fl">0.5</span></span>
<span id="cb113-10"><a href="#cb113-10"></a></span>
<span id="cb113-11"><a href="#cb113-11"></a><span class="co"># Using the default farthest neighbor algorithm to collapse genotypes</span></span>
<span id="cb113-12"><a href="#cb113-12"></a><span class="kw"><a href="../reference/mlg.filter.html">mlg.filter</a></span>(monpop, <span class="dt">distance =</span> bruvo.dist, <span class="dt">replen =</span> reps) &lt;-<span class="st"> </span>(<span class="fl">0.5</span><span class="op">/</span><span class="dv">13</span>) <span class="op">+</span><span class="st"> </span>e</span>
<span id="cb113-13"><a href="#cb113-13"></a>montabf &lt;-<span class="st"> </span><span class="kw"><a href="../reference/mlg.html">mlg.table</a></span>(monpop, <span class="dt">strata =</span> <span class="op">~</span>Symptom<span class="op">/</span>Year)</span></code></pre></div>
<p><img src="mlg_files/figure-html/unnamed-chunk-34-1.png" width="700" style="display: block; margin: auto;"></p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1"></a>(monstatf &lt;-<span class="st"> </span><span class="kw"><a href="../reference/diversity_stats.html">diversity_stats</a></span>(montabf, <span class="dt">CF =</span> myCF))</span></code></pre></div>
<pre><code>##        Index
## Pop            H        G    lambda       E.5        CF
##   BB_9  3.442117 23.81395 0.9580078 0.7541044 0.6093750
##   FR_9  3.003859 11.99001 0.9165973 0.5734961 0.2195122
##   BB_10 2.944439 19.00000 0.9473684 1.0000000 1.0000000
##   FR_10 3.861202 33.10974 0.9697974 0.6901987 0.2724014
##   BB_11 3.401197 30.00000 0.9666667 1.0000000 1.0000000
##   FR_11 2.754565  8.00766 0.8751196 0.4762511 0.3195876</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1"></a>monstat2 <span class="op">-</span><span class="st"> </span>monstatf <span class="co"># Take the difference from the unfiltered</span></span></code></pre></div>
<pre><code>##        Index
## Pop             H         G      lambda         E.5         CF
##   BB_9  0.1381408 2.1100971 0.003417969 -0.03959575 0.09375000
##   FR_9  0.1000406 0.4470973 0.002998215 -0.03615591 0.03902439
##   BB_10 0.0000000 0.0000000 0.000000000  0.00000000 0.00000000
##   FR_10 0.2056360 4.9915810 0.003956784 -0.04352013 0.06810036
##   BB_11 0.0000000 0.0000000 0.000000000  0.00000000 0.00000000
##   FR_11 0.3401226 2.4817496 0.029546179 -0.02609686 0.13402062</code></pre>
<p>We can see that filtered MLLs tend to be less diverse. This makes intuitive sense as it is creating larger classes of multilocus genotypes.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(monpop) &lt;-<span class="st"> "original"</span></span></code></pre></div>
</div>
<div id="jack-knife-rarefaction" class="section level2">
<h2 class="hasAnchor">
<a href="#jack-knife-rarefaction" class="anchor"></a>Jack-knife rarefaction</h2>
<p>The function <code><a href="../reference/diversity_ci.html">diversity_ci()</a></code> and <code><a href="../reference/diversity_boot.html">diversity_boot()</a></code> have the option to perform jack knife rarefaction calculations. This means that your data will be randomly sub-sampled to either the smallest population size, or whatever is specified in the parameter <code>n.rare</code>, whichever is bigger. Here’s an example with the previous data set:</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1"></a>(monrare &lt;-<span class="st"> </span><span class="kw"><a href="../reference/diversity_ci.html">diversity_ci</a></span>(montab, <span class="dt">n =</span> 100L, <span class="dt">rarefy =</span> <span class="ot">TRUE</span>, <span class="dt">raw =</span> <span class="ot">FALSE</span>))</span></code></pre></div>
<pre><code>## 
## Samples for rarefaction: 19</code></pre>
<p><img src="mlg_files/figure-html/unnamed-chunk-37-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>##          H H.est           H.ci    G G.est            G.ci lambda lambda.est
## BB_9  3.58  2.71 (2.492, 2.944) 25.9 13.93     (9.494, 19)  0.961      0.926
## FR_9  3.10  2.31 (1.922, 2.625) 12.4  8.75 (5.306, 12.448)  0.920      0.880
## BB_10 2.94  2.94           &lt;NA&gt; 19.0 19.00            &lt;NA&gt;  0.947      0.947
## FR_10 4.07  2.70 (2.362, 2.871) 38.1 13.98  (8.804, 17.19)  0.974      0.926
## BB_11 3.40  2.94           &lt;NA&gt; 30.0 19.00            &lt;NA&gt;  0.967      0.947
## FR_11 3.09  2.32  (1.831, 2.64) 10.5  8.42   (4.4, 12.448)  0.905      0.871
##            lambda.ci   E.5 E.5.est         E.5.ci
## BB_9  (0.895, 0.947) 0.715   0.907     (0.797, 1)
## FR_9   (0.811, 0.92) 0.537   0.831   (0.7, 0.912)
## BB_10           &lt;NA&gt; 1.000   1.000           &lt;NA&gt;
## FR_10 (0.886, 0.942) 0.647   0.919 (0.775, 0.972)
## BB_11           &lt;NA&gt; 1.000   1.000           &lt;NA&gt;
## FR_11  (0.773, 0.92) 0.450   0.772   (0.627, 0.9)</code></pre>
<p>This can give you comparable estimates of diversity when not all samples are of equal size.</p>
</div>
</div>
<div id="clone-correction" class="section level1">
<h1 class="hasAnchor">
<a href="#clone-correction" class="anchor"></a>Clone Correction</h1>
<p>Clone-correction works hierarchically and only uses the first MLG copy encountered in the data per population. This is straightforward for naïve MLGs, but for MLLs collapsed by genetic distance or custom MLLs, this might change the results very slightly. As an example, let’s look at the <code>monpop</code> filtered MLLs that we created earlier.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1"></a><span class="kw"><a href="../reference/mll-method.html">nmll</a></span>(monpop, <span class="st">"original"</span>)</span></code></pre></div>
<pre><code>## [1] 264</code></pre>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1"></a><span class="kw"><a href="../reference/mll-method.html">nmll</a></span>(monpop, <span class="st">"contracted"</span>)</span></code></pre></div>
<pre><code>## [1] 214</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1"></a><span class="kw"><a href="../reference/mll-method.html">mll</a></span>(monpop) &lt;-<span class="st"> "contracted"</span></span></code></pre></div>
<p>To show how the order of the samples can affect the sampling, we will take the sum of all pairwise distances between clone-corrected samples (corrected without respect to populations):</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1"></a>monpop <span class="op">%&gt;%</span></span>
<span id="cb127-2"><a href="#cb127-2"></a><span class="st">  </span><span class="kw"><a href="../reference/clonecorrect.html">clonecorrect</a></span>(<span class="dt">strata =</span> <span class="ot">NA</span>) <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># 1. clone correct whole data set</span></span>
<span id="cb127-3"><a href="#cb127-3"></a><span class="st">  </span><span class="kw"><a href="https://rdrr.io/r/stats/dist.html">dist</a></span>() <span class="op">%&gt;%</span><span class="st">                     </span><span class="co"># 2. calculate distance</span></span>
<span id="cb127-4"><a href="#cb127-4"></a><span class="st">  </span><span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>()                          <span class="co"># 3. take the sum of the distance</span></span></code></pre></div>
<pre><code>## [1] 90268.73</code></pre>
<p>Now, what happens when we randomly sample individuals?</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1"></a><span class="kw"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span>(<span class="dv">999</span>)</span>
<span id="cb129-2"><a href="#cb129-2"></a>monpop[<span class="kw"><a href="https://rdrr.io/r/base/sample.html">sample</a></span>(<span class="kw">nInd</span>(monpop))] <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># 1. shuffle samples</span></span>
<span id="cb129-3"><a href="#cb129-3"></a><span class="st">  </span><span class="kw"><a href="../reference/clonecorrect.html">clonecorrect</a></span>(<span class="dt">strata =</span> <span class="ot">NA</span>) <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># 2. clone correct whole data set</span></span>
<span id="cb129-4"><a href="#cb129-4"></a><span class="st">  </span><span class="kw"><a href="https://rdrr.io/r/stats/dist.html">dist</a></span>() <span class="op">%&gt;%</span><span class="st">                     </span><span class="co"># 3. calculate distance</span></span>
<span id="cb129-5"><a href="#cb129-5"></a><span class="st">  </span><span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>()                          <span class="co"># 4. take the sum of the distance</span></span></code></pre></div>
<pre><code>## [1] 90257.92</code></pre>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1"></a><span class="kw"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span>(<span class="dv">1000</span>)</span>
<span id="cb131-2"><a href="#cb131-2"></a>monpop[<span class="kw"><a href="https://rdrr.io/r/base/sample.html">sample</a></span>(<span class="kw">nInd</span>(monpop))] <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># 1. shuffle samples</span></span>
<span id="cb131-3"><a href="#cb131-3"></a><span class="st">  </span><span class="kw"><a href="../reference/clonecorrect.html">clonecorrect</a></span>(<span class="dt">strata =</span> <span class="ot">NA</span>) <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># 2. clone correct whole data set</span></span>
<span id="cb131-4"><a href="#cb131-4"></a><span class="st">  </span><span class="kw"><a href="https://rdrr.io/r/stats/dist.html">dist</a></span>() <span class="op">%&gt;%</span><span class="st">                     </span><span class="co"># 3. calculate distance</span></span>
<span id="cb131-5"><a href="#cb131-5"></a><span class="st">  </span><span class="kw"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>()                          <span class="co"># 4. take the sum of the distance</span></span></code></pre></div>
<pre><code>## [1] 90311.96</code></pre>
<p>Notice how we are getting different results based on the order of samples. This does not mean that the procedure doesn’t work, it just means that we must be careful when clone-correcting modified multilocus genotypes.</p>
</div>
<div id="conclusions" class="section level1">
<h1 class="hasAnchor">
<a href="#conclusions" class="anchor"></a>Conclusions</h1>
<p>We have demonstrated here new methods for treating multilocus genotypes on microsatellite data, but it is important to remember that all of these functions can work with any source of data stored in either a <strong>genclone</strong> or <strong>snpclone</strong> (derived from <strong>genlight</strong>) object. Especially with <code><a href="../reference/mlg.filter.html">mlg.filter()</a></code>, these new functions will allow for a more flexible analysis of WGS data of clonal organisms where true clones may differ by more than a few mutations/errors/missing data. As with all analyses, it is important to understand the algorithms used and take them into account when interpreting results.</p>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-arnaud2007standardizing">
<p>Arnaud-Haond, Sophie, Carlos M Duarte, Filipe Alberto, and Ester A Serrão. 2007. “Standardizing Methods to Address Clonality in Population Studies.” <em>Molecular Ecology</em> 16 (24): 5115–39. <a href="https://doi.org/10.1111/j.1365-294X.2007.03535.x">https://doi.org/10.1111/j.1365-294X.2007.03535.x</a>.</p>
</div>
<div id="ref-bailleul2016rclone">
<p>Bailleul, Diane, Solenn Stoeckel, and Sophie Arnaud-Haond. 2016. “RClone: A Package to Identify MultiLocus Clonal Lineages and Handle Clonal Data Sets in R.” Edited by Timothée Poisot. <em>Methods in Ecology and Evolution</em> 7 (8): 966–70. <a href="https://doi.org/10.1111/2041-210x.12550">https://doi.org/10.1111/2041-210x.12550</a>.</p>
</div>
<div id="ref-Bruvo:2004">
<p>Bruvo, Ruzica, Nicolaas K. Michiels, Thomas G. D’Souza, and Hinrich Schulenburg. 2004. “A Simple Method for the Calculation of Microsatellite Genotype Distances Irrespective of Ploidy Level.” <em>Molecular Ecology</em> 13 (7): 2101–6. <a href="https://doi.org/10.1111/j.1365-294X.2004.02209.x">https://doi.org/10.1111/j.1365-294X.2004.02209.x</a>.</p>
</div>
<div id="ref-everhart2014finescale">
<p>Everhart, Sydney, and Harald Scherm. 2015. “Fine-Scale Genetic Structure of <em>Monilinia Fructicola</em> During Brown Rot Epidemics Within Individual Peach Tree Canopies.” <em>Phytopathology</em> 105 (4): 542–49. <a href="https://doi.org/10.1094/PHYTO-03-14-0088-R">https://doi.org/10.1094/PHYTO-03-14-0088-R</a>.</p>
</div>
<div id="ref-goss2009population">
<p>Goss, Erica M, Meg Larsen, Gary A Chastagner, Donald R Givens, and Niklaus J Grünwald. 2009. “Population Genetic Analysis Infers Migration Pathways of Phytophthora Ramorum in Us Nurseries.” <em>PLoS Pathog</em> 5 (9): e1000583.</p>
</div>
<div id="ref-kamvar2015novel">
<p>Kamvar, Zhian N, Jonah C Brooks, and Niklaus J Grünwald. 2015. “Novel R tools for analysis of genome-wide population genetic data with emphasis on clonality.” <em>Frontiers in Genetics</em> 6: 208. <a href="https://doi.org/10.3389/fgene.2015.00208">https://doi.org/10.3389/fgene.2015.00208</a>.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">

        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#abstract">Abstract</a></li>
      <li><a href="#introduction">Introduction</a></li>
      <li>
<a href="#multilocus-genotype-flavors">Multilocus Genotype Flavors</a><ul class="nav nav-pills nav-stacked">
<li><a href="#na%C3%AFve-original">Naïve (“original”)</a></li>
      <li><a href="#filtered-contracted">Filtered (“contracted”)</a></li>
      <li><a href="#custom-custom">Custom (“custom”)</a></li>
      </ul>
</li>
      <li>
<a href="#diversity-analysis">Diversity Analysis</a><ul class="nav nav-pills nav-stacked">
<li><a href="#basic-statistics">Basic Statistics</a></li>
      <li><a href="#confidence-intervals">Confidence Intervals</a></li>
      <li><a href="#custom-statistics">Custom Statistics</a></li>
      <li><a href="#jack-knife-rarefaction">Jack-knife rarefaction</a></li>
      </ul>
</li>
      <li><a href="#clone-correction">Clone Correction</a></li>
      <li><a href="#conclusions">Conclusions</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>



      <footer><div class="copyright">
  <p>Developed by Zhian N. Kamvar, Javier F. Tabima, Jonah C. Brooks.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
